services:
  app:
    image: alexafanasyev/calc:1.0.1
    container_name: calc_bot
    restart: no
    shm_size: 500mb
    env_file:
      - secrets/calc.env
      - secrets/database.env
    environment:
      DB_CONTAINER_NAME: calc_db
    ports:
      - "8585:8585"
    networks:
      - calc
    depends_on:
      - db
  db:
    image: 'postgres:alpine3.19'
    container_name: calc_db
    restart: unless-stopped
    shm_size: 500mb
    env_file:
      - secrets/database.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - calc
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

networks:
  calc:
    name: calc
    driver: bridge
