# Spring configuration
spring:
  profiles:
    default: dev

  mvc:
    format:
      date: dd.MM.yyyy
      date-time: yyyy.MM.dd HH:mm:ss
      time: HH:mm:ss
  data:
    rest:
      default-media-type: application/json

# Server configuration
server:
  port: 8585
  servlet:
    session:
      cookie:
        http-only: true
      encoding:
        charset: UTF-8
      timeout: 60m

# Application configuration (tax in %)
calc:
  service:
    month-salary: 180000
    kata-tax: 0.17
    airbag: 30000
    mandatory: 46000
    apartment: 29000
    julia-needs: 13000
    julia-loan: 8300

# Logging configuration
logging:
  level:
    org.springframework: info
    root: info
  charset:
    console: UTF-8
springdoc:
  show-login-endpoint: true