# spring config
spring:
  profiles:
    default: dev

# server config
server:
  port: 8585
  servlet:
    session:
      cookie:
        http-only: true
    encoding:
      charset: UTF-8

  # app config (tax in %)
calc:
  service:
    month-salary: 180000
    kata-tax: 0.17
    airbag: 30000
    mandatory: 46000
    apartment: 29000
    julia-needs: 13000
    julia-loan: 8300

logging:
  level:
    org.springframework: info
    root: info
  charset:
    console: UTF-8


