# Spring configuration
spring:
  main:
    banner-mode: off
  profiles:
    default: dev
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${PG_USER:postgresUser}
    password: ${PG_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    properties:
      hibernate:
        default_schema: calc
        format_sql: true
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  # Liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    default-schema: calc

# Server configuration
server:
  port: 8585
  servlet:
    session:
      cookie:
        http-only: true
      timeout: 60m

# Application configuration (tax in %)
calc:
  service:
    month-salary: 180000
    kata-tax: 0.17
    airbag: 30000
    mandatory: 46000
    apartment: 29000
    julia-needs: 13000
    julia-loan: 8300

token:
  signing:
    key: ${JWT_SECRET_BASE64}
    expiration: 3600000

# Logging configuration
logging:
  level:
    org.springframework: info
    root: info
  charset:
    console: UTF-8

telegram:
  bot-token: ${TG_BOT_TOKEN}
#  Id главного пользователя telegram, которому доступно управление ботом
  creator-id: 371923388