logging:
  level:
    root: debug

telegram:
  api-key: {set me on server}
  bot-name: test_alexaf_moneycalc_bot

spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/calc
    username: postgresUser
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none
        default_schema: public
    open-in-view: false

  # Liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    default-schema: public


