# Spring configuration
spring:
  profiles:
    default: dev
  application:
    name: calc
    version: 1.0
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/calc
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: public
        format_sql: true
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  # Liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    default-schema: public

# Server configuration
server:
  port: 8585
  servlet:
    session:
      cookie:
        http-only: true
      timeout: 60m

# Application configuration (tax in %)
calc:
  service:
    month-salary: 180000
    kata-tax: 0.17
    airbag: 30000
    mandatory: 46000
    apartment: 29000
    julia-needs: 13000
    julia-loan: 8300

token:
  signing:
    key: ${JWT_SECRET_KEY_BASE64}
    expiration: 3600000

# Logging configuration
logging:
  level:
    org.springframework: info
    root: info
  charset:
    console: UTF-8

telegram:
  api-key: ${TG_API_KEY}