# Spring configuration
spring:
  main:
    banner-mode: off
  profiles:
    default: dev
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_CONTAINER_NAME:localhost}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA}
        format_sql: true
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  # Liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    default-schema: ${DEFAULT_SCHEMA}

# Application configuration (tax in %)
calc:
  service:
    month-salary: 180000
    kata-tax: 0.17
    airbag: 30000
    mandatory: 46000
    apartment: 29000
    julia-needs: 13000
    julia-loan: 8300

# Logging configuration
logging:
  level:
    org.springframework: info
    root: info
  charset:
    console: UTF-8

telegram:
  bot-token: ${TG_BOT_TOKEN}
  bot-name: ${TG_BOT_NAME}
  #  Id главного пользователя telegram, которому доступно управление ботом
  creator-id: 371923388
  cache: true