logging:
  level:
    root: debug

telegram:
  api-key: {set me on server}
  bot-name: test_alexaf_moneycalc_bot

spring:
  # Database configuration
  datasource:
    url: jdbc:h2:file:./data/sampledb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    database:
      name: sampledb
      schema: public
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: create-drop
    open-in-view: false

  # Liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: false


