# spring config
spring:
  profiles:
    active: dev
    default: dev

# server config
server:
  port: 8585

# app config (tax in %)
calc:
  service:
    # ?? ? ?????
    month-salary: 180000
    # % ??? Kata Academy
    kata-tax: 0.17
    # ??????????? ?????? ?? ??????? ????????????
    airbag: 30000
    # ???????????? ??????? (???, ???????, ???????? ? ?.?.)
    mandatory: 46000
    # ????????
    apartment: 29000
    # ??????????? ??? ???
    julia-needs: 13000
    # ????
    julia-loan: 8300

  repository:
    enabled: false
    filePath: C:\Users\?????????????\OneDrive\??????? ????\Kata ??????.xlsx

logging:
  level:
    org.springframework: info
    com.alexaf.moneycalc: debug
    root: info
  charset:
    console: UTF-8

telegram:
  api-key: {set me on server}



