package com.alexaf.salarycalc.goal;

public enum GoalType {
    FIXED_AMOUNT_WITH_DEADLINE,
    FIXED_AMOUNT_WITHOUT_DEADLINE,
    MONTHLY_FIXED_AMOUNT,
    MONTHLY_PERCENTAGE_WITH_TOTAL,
    MONTHLY_PERCENTAGE_WITH_DEADLINE,
    MONTHLY_PERCENTAGE_WITHOUT_DEADLINE
}
